### ISSUE TITLE
Any reason not to support Worker Roles?

### ISSUE THREAD

**Issue by bytenik** [MRCollective/AzureWebFarm.OctopusDeploy#22]
Is there any reason to not support worker roles? I know web roles generally cut it, but I need a worker because I have a service that runs on port 80 but not through IIS.

**Comment by johnkattenhorn** [comment]
Hey @robdmoore, 

Now then I totally agree with the points about not using Worker Roles when Web Roles will do the job but IF I was forced by outside influences to use Worker Roles do you think we could actually make this work ?

**Comment by robdmoore** [comment]
I'm more than happy to take a pull request that provides a configuration option to not call all of the IIS code. Off the top of my head that should be the only bit that fails on a worker role.

**Comment by johnkattenhorn** [comment]
OK, I've done some work to support worker roles which I've committed to my fork. I'm now kinda thinking "ok so you have a running tentacle on a worker role - what now ?" I'm wondering what the deploy project steps should look like in order to deploy the 'real' worker code.

I'm guessing it should be something like stop role, deploy code, start role, any thoughts @robdmoore ?

**Comment by robdmoore** [comment]
Not quite sure what you mean in relation to the "deploy project steps"?

The commits in your fork look OK, there is a couple of minor things in there we can resolve when you raise a PR e.g. what the upgrade path is for people that do an `Update-Package` etc.

**Comment by johnkattenhorn** [comment]
My question was related to what should the NuGet look like and how should it deploy new code since I now have a Octopus Tentacle available to me on the Cloud Service Machine. In the 'normal way of things I would have used the Azure Step or similar to use cspack to deploy the cloud service but now I have an agent directly on the machine I wondering what I should do.

Should I try to stop the WorkerRole instance on the machine, copy the code over the top and then re-start it. 

To be honest I can't even remember what my Octopus Project Steps where when I used this against a Web Role, did we document that last year anywhere ?

**Comment by johnkattenhorn** [comment]
It's starting to dawn on me this might not work after all because (Apologies I'm speaking to myself right now) :

1) There's no way I know of to stop the Worker Role Processes on the Machine which is running the Tentacle, so there no way to guarantee that files will not be locked or the application state will be consistent when Octopus Installs the NuGet in the project.

2) In my case I need access to about 15 UDP ports defined in the ServiceConfiguration which are part of an internal load balancer so I'm think even swapping this out for a Windows Service may not work although it could be that the Worker Role Instance is giving access to them and doesn't relate to being a worker role.

**Comment by robdmoore** [comment]
Hi @johnkattenhorn I suspect what you are talking about is trying to use Octopus Deploy to deploy an actual worker role (i.e. a cloud service project in Visual Studio).

This definitely won't be (easily) possible and I wouldn't recommend trying to do it.

I'd deploy the Worker Role with a tentacle using this project (including whatever service definition you need - ports, certificates etc.) and then use Octopus to deploy Windows Services on the machine.
